# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 026588a72ce59ca0c188fa90c4660fff7ed9f4275ae931f4f34886f0fbd231481a9fe8376b6436889ae31835cef1e49a79500476d349358a112c21672dac9945

test:
  secret_key_base: cbedca5ab646a5bfc7b145a72015f894279db0fbd688e5757a19b16f548f1f01deaf20cb1782dd9265ef4a2807eb0c7562208f2c724f9f7e68481958b080b1bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
